# Example Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
  - index.md
  - about.md
  - contact.md

footer: 'follow us on <a href="https://code-bebop.github.com/">Github</a>'

#style: light # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console

plugins:
  - jekyll-seo-tag
